; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
board_build.partitions = default_8MB.csv

build_flags =
    -DBOARD_HAS_PSRAM

lib_deps =
  knolleary/PubSubClient @ ^2.8
  adafruit/Adafruit GFX Library @ ^1.12.6
  adafruit/Adafruit SSD1306 @ ^2.5.16


; O módulo ESP32-S3-WROOM-1-N8R8 usa 8 MB de SRAM
; Então, para o build é necessário usar Octal SPI (opi)
; https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32s3/esp32-s3-devkitc-1/user_guide_v1.1.html
[env:esp32-s3-hardware]
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
build_flags =
    ${env.build_flags}
    -DARDUINO_USB_CDC_ON_BOOT=1

; Wokwi suporta até 4MB de SRAM
; Então, para simulação é necessário usar Quad SPI (qspi)
; https://docs.wokwi.com/guides/esp32#simulation-features
[env:esp32-s3-wokwi]
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qspi

; Ativa informações de debug e desabilita optimizações automáticas do compiler
; https://docs.platformio.org/en/latest/projectconf/build_configurations.html#build-configurations
build_type = debug

; Permite customizar a configuração de debug
; https://docs.platformio.org/en/latest/plus/debugging.html#tools-debug-probes
debug_tool = custom

; Porta de Debug configurada para o Wokwi, em wokwi.toml
; https://docs.platformio.org/en/latest/projectconf/sections/env/options/debug/debug_port.html
debug_port = localhost:3333

debug_init_cmds = target extended-remote $DEBUG_PORT