; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = wokwi

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
board_build.partitions = default_8MB.csv

; O módulo ESP32-S3-WROOM-1-N8R8 contém 8 MB de PSRAM
; Então, é necessário usar Octal SPI (opi)
; https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32s3/esp32-s3-devkitc-1/user_guide_v1.1.html
;
; Wokwi também suporta Octal SPI, sendo necessário configurar no diagram.json.
; https://docs.wokwi.com/guides/esp32#flash-and-memory-size 
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi

build_flags =
    -DBOARD_HAS_PSRAM           ; Incluí o driver PSRAM no build
  
    -DARDUINO_USB_CDC_ON_BOOT=1 ; Emulação de porta Serial virtual via USB
                                ;
                                ; 5.2.1.8 USB Serial/JTAG Controller
                                ; https://documentation.espressif.com/esp32-s3-wroom-1_wroom-1u_datasheet_en.pdf

monitor_speed = 115200

lib_deps =
  knolleary/PubSubClient @ ^2.8
  adafruit/Adafruit GFX Library @ ^1.12.6
  adafruit/Adafruit SSD1306 @ ^2.5.16



; Build para Hardware, sem configuração de debug
[env:hardware]
build_type = release



; Configuração de Debug para o simulador do Wokwi
; https://docs.platformio.org/en/latest/plus/debugging.html
;
; Esta configuração permite a utilização de breakpoints no VSCode.
[env:wokwi]

; Ativa informações de debug e desabilita optimizações automáticas do compiler
; https://docs.platformio.org/en/latest/projectconf/build_configurations.html#build-configurations
build_type = debug

; Permite customizar a configuração de debug
; https://docs.platformio.org/en/latest/plus/debugging.html#tools-debug-probes
debug_tool = custom

; Porta de Debug configurada para o Wokwi, em wokwi.toml
; https://docs.wokwi.com/vscode/debugging
; https://docs.platformio.org/en/latest/projectconf/sections/env/options/debug/debug_port.html
debug_port = localhost:3333

; Ligação à porta de debug do Wokwi
debug_init_cmds = target extended-remote $DEBUG_PORT